      eureka:
          instance:
            prefer-ip-address: true
          client:
            fetch-registry: true
            register-with-eureka: true

          eureka:
            client:
              serviceUrl:
                defaultZone: http://localhost:8761/eureka
